export const DEVELOPER_DASHBOARD_REQUEST = "DEVELOPER_DASHBOARD_REQUEST"
export const DEVELOPER_DASHBOARD_SUCCESS = "DEVELOPER_DASHBOARD_SUCCESS"
export const DEVELOPER_DASHBOARD_FAIL = "DEVELOPER_DASHBOARD_FAIL"
