export const FETCH_SKILLS_REQUEST = "FETCH_SKILLS_REQUEST"
export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS"
export const FETCH_SKILLS_FAIL = "FETCH_SKILLS_FAIL"

export const ADD_SKILL_REQUEST = "ADD_SKILL_REQUEST"
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS"
export const ADD_SKILL_FAIL = "ADD_SKILL_FAIL"

export const REMOVE_SKILL_REQUEST = "REMOVE_SKILL_REQUEST"
export const REMOVE_SKILL_SUCCESS = "REMOVE_SKILL_SUCCESS"
export const REMOVE_SKILL_FAIL = "REMOVE_SKILL_FAIL"
