/**
 * All Login action constants
 */
export const UPDATE_EMAIL = "UPDATE_EMAIL"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_RESET_EMAIL = "UPDATE_RESET_EMAIL"
export const USER_SIGNIN = "USER_SIGNIN"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG"
export const SHOW_LOST_PASSWORD_DIALOG = "SHOW_LOST_PASSWORD_DIALOG"
export const UPDATE_PROJECT_LIST = "UPDATE_PROJECT_LIST"
