export const UPDATE_FORM_VALUE = "UPDATE_FORM_VALUE"
export const USER_ORGANIZATION = "USER_ORGANIZATION"
export const USER_ORGANIZATION_SUCCESS = "USER_SIGNIN_SUCCESS"
export const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG"
